name: TESTS OWASP ZAP
on: 
  schedule:
    - cron: '0 3 * * *'  # Executar todos os dias às 3h UTC
  push:
    branches:
      - master  # substitua pelo nome da sua branch principal
  pull_request:
    branches:
      - master  # substitua pelo nome da sua branch principal
  workflow_dispatch: # Permite o acionamento manual do workflow
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Executar varredura ZAP
        run: |
          docker run -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t https://www.example.com -g gen.conf -r testreport.html || true

      - name: Salvar relatório como artefato
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: testreport.html
