jobs:
  example_job_name: # Nome do trabalho
    runs-on: ubuntu-latest # Sistema operacional em que ser치 executado

    steps: # Etapas do trabalho
      - name: Checkout do reposit칩rio
        uses: actions/checkout@v2

      - name: Executar varredura ZAP e copiar relat칩rio
        run: |
          docker run --name zap-container -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t https://www.example.com -r /zap/wrk/testreport.html || true
          docker cp zap-container:/zap/wrk/testreport.html testreport.html

      - name: Salvar relat칩rio como artefato
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: testreport.html
