name: OWASP ZAP
on: 
  schedule:
    - cron: '0 3 * * *'  # Executar todos os dias às 3h UTC
  push:
    branches:
      - maste  # substitua pelo nome da sua branch principal
  pull_request:
    branches:
      - maste  # substitua pelo nome da sua branch principal
  workflow_dispatch: # Permite o acionamento manual do workflow
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: maste

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://juice-shop.herokuapp.com/'
          rules_file_name: './zap/rules.tsv'
          cmd_options: '-a'

      - name: Check ZAP Scan Results
        run: |
          # Verificar se há vulnerabilidades graves (por exemplo, HIGH, MEDIUM)
          if grep -iq 'Medium' *.html || grep -iq 'High' *.html; then
            echo "Vulnerabilidades médias ou altas encontradas. Workflow falhou."
            exit 1
            else
              echo "Não foram encontradas vulnerabilidades médias ou altas."
            fi

