name: Wapiti Security Scan

on:
  schedule:
    - cron: '0 3 * * *'  # Executar todos os dias às 3h UTC
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # Permite o acionamento manual do workflow

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Wapiti
        run: |
          sudo apt-get update
          sudo apt-get install wapiti -y

      - name: entra em tests as pastas
        run: sudo bash -c 'cd ./tests && ls -la'

      - name: Run Wapiti Scan
        run: |
           wapiti -u https://juice-shop.herokuapp.com -f html -o ./tests/report.html

      - name: verifica as pastas
        run: ls ./tests

      - name: Upload Wapiti Report
        uses: actions/upload-artifact@v2
        with:
          name: wapiti-report
          path: ./tests/report.html/*
