name: Wapiti Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Permite o acionamento manual do workflow

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create temporary directory
        run: mkdir -p $HOME/temp_reports

      - name: Install Wapiti
        run: |
          sudo apt-get update
          sudo apt-get install wapiti -y

      - name: Run Wapiti Scan
        run: |
          cd $HOME/temp_reports
          wapiti -u https://juice-shop.herokuapp.com -f html -o report.html
      
      - name: verifica as pastas
        run: ls -a

      - name: Upload Wapiti Report
        uses: actions/upload-artifact@v2
        with:
          name: wapiti-report
          path: $HOME/temp_reports/report.html/*
